export const Colors = {
    light:{
        accent: '#061E86',
        secondary: '#838383',
        primary: '#03D858',
        background: '#ffffff',
        text: '#2A2A3A',
        categoryColor: '#061E86',
        titleText: '#20d497',
        statusBarBG: '#061E86',
        settingsBG: '#ffffff',
        settingsSecondBG: '#dddddd',
        trackColorDisabled : '#cccccc',
        descriptionColor: '#000000',
        dividerColor : '#cccccc',
        dividerColorSecond : '#cccccc',
        versionColor : '#777777',
        buttonText: '#ffffff',
        newsCardIcon: '#061E86',
    },

    dark:{
        accent: '#20d497',
        secondary: '#838383',
        primary: '#20d497',
        background: '#2b2a3a',
        text: '#ffffff',
        categoryColor: '#ffffff',
        titleText: '#20d497',
        statusBarBG: '#2b2a3a',
        settingsBG: '#2b2a3a',
        settingsSecondBG: '#1b1a2a',
        trackColorDisabled : '#cccccc',
        descriptionText: '#ffffff',
        dividerColor : '#20d497',
        dividerColorSecond : '#20d497',
        versionColor : '#777777',
        buttonText: '#000000',
        newsCardIcon: '#20d497',
    }

};
